name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: andrezanella
          password: toxkos-nexMab-zyxno7

      - name: Get commit count for versioning
        id: get-version
        run: echo "::set-output name=version::$(git rev-list --count HEAD)"

      - name: Build and push Docker images
        run: |
          VERSION="v1.${{ steps.get-version.outputs.version }}"
          for dir in */ ; do
            dir=${dir%/}  # Remove trailing slash
            if [ -f "$dir/Dockerfile" ]; then
              if [[ ${{ github.ref }} == refs/heads/main ]]; then
                IMAGE_REPO=file_app/$dir
              elif [[ ${{ github.ref }} == refs/heads/develop ]]; then
                IMAGE_REPO=file_app_test/$dir
              else
                echo "Unsupported branch. Skipping build."
                exit 0  # Exit without failure
              fi

              docker build -t $IMAGE_REPO:$VERSION -f $dir/Dockerfile $dir
              docker tag $IMAGE_REPO:$VERSION $IMAGE_REPO:latest
              docker push $IMAGE_REPO:$VERSION
              docker push $IMAGE_REPO:latest
            else
              echo "Dockerfile not found in $dir, skipping."
            fi
          done

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: andrezanella
          password: toxkos-nexMab-zyxno7

      - name: Deploy to environment
        run: |
          if [[ ${{ github.ref }} == refs/heads/main ]]; then
            IMAGE_REPO=file_app
          elif [[ ${{ github.ref }} == refs/heads/develop ]]; then
            IMAGE_REPO=file_app_test
          else
            echo "Unsupported branch. Skipping deploy."
            exit 0  # Exit without failure
          fi

          docker-compose -f docker-compose.yml pull
          docker-compose -f docker-compose.yml up -d
